version: '3'
services:
  db:
    restart: unless-stopped
    image: postgres:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
    - "5432:5432"
  redis:
    restart: unless-stopped
    image: redis:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
    - 'redis:/data'
    ports:
    - "6379:6379"
volumes:
  redis: