loglevel = "ERROR"

[backends]
[backends.zalupa]
        [backends.zalupa.servers.nasweb]
#            url = "http://192.168.1.11:5000"
#            url = "http://172.17.0.1:5000"
#            url = "https://musicroom-bucket.s3.amazonaws.com/index.html"
#            url = "https://musicroom-bucket.s3.amazonaws.com/index.html"
            url = "http://musicroom-bucket.s3-website.eu-central-1.amazonaws.com"

[frontends]
        [frontends.front]
                backend = "zalupa"
        [frontends.front.routes.front]
#                rule = "musicroom.ml/front"
#                rule = "Host:front.musicroom.ml;AddSufix:/index.html;"
                rule = "Host:front.musicroom.ml;"
                regex = "^https?://front.musicroom.ml/(.*)"
#                replacement = "https://front.musicroom.ml/"
#                regex = "(http:\\/\\/[^\\/]+\\/([^\\?]+)[^\\/])$"
#                replacement = "$1/"
                replacement = "https://front.musicroom.ml/index.html"

                permanent = true