# variable {{host}}  located in http-client.env.json file (the root of project)
# variable {{token}} in http-client.private.env.json

# регистрация
POST {{host}}/auth/registration/
Content-Type: application/json

{
  "username": "wartoxy@gmail.com",
  "email": "wartoxy@gmail.com",
  "password1": "q12we34rt56y",
  "password2": "q12we34rt56y"
}

### verify email

POST {{host}}/auth/verify-email/
Content-Type: application/json

{
  "key": "MQ:1hFnhO:CuCgGhBHg02jFdDeP5z04PER2cs"
}

### вводите сюда логин и пароль - получаете в ответ токен

POST {{host}}/auth/token/
Content-Type: application/json

{
  "username": "wartoxy@gmail.com",
  "email": "wartoxy@gmail.com",
  "password": "q12we34rt56y"
}

### текущий пользователь (профиль)

GET {{host}}/auth/user
Authorization: JWT {{token}}
Content-Type: application/json

###

GET {{host}}/auth/google/url
Authorization: JWT {{token}}
Content-Type: application/json

###

GET {{host}}/api/
Authorization: JWT {{token}}
Content-Type: application/json

###

GET {{host}}/api/playlists/
Authorization: JWT {{token}}
Content-Type: application/json

###

POST {{host}}/api/playlists/
Authorization: JWT {{token}}
Content-Type: application/json

{
  "name": "SUKA",
  "is_public": true,
  "is_active": true
//  "time_from": "string",
//  "time_to": "string",
//  "owners": [
//    "string"
//  ]
}

###

GET {{host}}/api/tracks/
Authorization: JWT {{token}}
Content-Type: application/json

### удалить все данные из базы

GET {{host}}/management/clear-data
Content-Type: application/json

### заполнить тестовыми (аналогично ./manage.py add_content; main/management/commands/add_content.py)

GET {{host}}/management/fill-data
Content-Type: application/json

###