# variable {{host}}  located in http-client.env.json file (the root of project)
# variable {{token}} in http-client.private.env.json

### обычная регистрация. пока что возвращает ошибку потому что пытается отправить почту которая не настроена
### но юзер создается нормально, игнорируйте ошибку

# это ошибка из-за почты кажется
# Exception Type: ConnectionRefusedError at /auth/registration/
# Exception Value: [Errno 61] Connection refused
# Request information:
# USER: AnonymousUser
POST {{host}}/auth/registration/
Content-Type: application/json

{
  "username": "suka",
  "email": "suka@gmail.com",
  "password1": "q12we34rt56y",
  "password2": "q12we34rt56y"
}

### вводите сюда логин и пароль - получаете в ответ токен

POST {{host}}/auth/login/
Content-Type: application/json

{
  "username": "suka",
  "password": "q12we34rt56y"
}

### вводите сюда логин и пароль - получаете в ответ токен

POST {{host}}/auth/token/
Content-Type: application/json

{
  "username": "suka",
  "email": "suka@gmail.com",
  "password": "q12we34rt56y"
}

### рефреш токена
POST {{host}}/auth/token-refresh/?token={{token}}
/auth/token-refresh/

### с токеном можно ходить по защищенным урлам

GET {{host}}/auth/user
Authorization: JWT {{token}}
Content-Type: application/json

{
}

###

GET {{host}}/auth/google/url
Authorization: JWT {{token}}
Content-Type: application/json

###

GET {{host}}/api/playlists/
Authorization: JWT {{token}}
Content-Type: application/json

###

GET {{host}}/api/
Authorization: JWT {{token}}
Content-Type: application/json

###

###

GET {{host}}/api/playlists/
Authorization: JWT {{token}}
Content-Type: application/json

###

OPTIONS {{host}}/api/playlists/
Authorization: JWT {{token}}
Content-Type: application/json

###