# Generated by Django 2.1.7 on 2019-03-24 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='owner',
        ),
        migrations.AddField(
            model_name='playlist',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
