# Generated by Django 2.2 on 2019-04-23 15:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='place',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
