# Generated by Django 2.1.7 on 2019-04-14 09:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190406_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
